version: "3.8"
services:

    redis_db:
        image: redis:latest
        ports:
            - "6379"
        networks:
            - the_network
        container_name: redis_db  
        tty: true
        stdin_open: true   

    snmpd:
        image: yuvaltoker/snmpd:1.0
        #build:
        #    context: ../snmpd/.
        #    dockerfile: ../dockerfiles/build-snmpd
        networks:
            - the_network
        depends_on:
            - redis_db
        container_name: snmpd
        tty: true
        stdin_open: true

    sender:
        image: yuvaltoker/snmp-server1.0
        #build:
        #    context: ../sender/.
        #    dockerfile: ../dockerfiles/snmp-sender
        networks:
            - the_network
        depends_on:
            - redis_db
            - snmpd
            - server
        environment:
            - SERVER_HOST=sam-server
            - SERVER_PORT=3044
            - PRIV_PASS=yuval12345
            - AUTH_PASS=yuval12321
            - USER_NAME=mynewuser
        container_name: sender
        tty: true
        stdin_open: true

    server:
        image: samyon196/snmp_demo_server:1.0.0
        environment:
            - PORT_TCP_SNMP=3044
        networks:
            - the_network
        container_name: sam-server
        tty: true
        stdin_open: true
        # sending snmpget request:
        # { "method":"GET","destination":"snmpd:1662","oid":"1.3.6.1.4.1.8073.1.1.4.0","name":"bla","type":"snmpRequest","time":"132","hash":"" }
        # sending snmpset request
        #{ "method":"SET","destination":"snmpd:1662","oid":"1.3.6.1.4.1.8073.1.1.4.0","name":"bla","type":"snmpRequest","time":"132","hash":"12321", "value":"2", "dataType":"i" }


networks:
    the_network:
        name: the_network
        driver: bridge