version: "3.8"
services:

    redis_db:
        image: redis:latest
        ports:
            - "6379"
        networks:
            - the_network
        container_name: redis_db  
        tty: true
        stdin_open: true   

    snmpd:
        build:
            context: ../snmpd/.
            dockerfile: ../dockerfiles/build-snmpd
        networks:
            - the_network
        depends_on:
            - redis_db
        container_name: snmpd
        tty: true
        stdin_open: true

    sender:
        build:
            context: ../sender/.
            dockerfile: ../dockerfiles/snmp-sender
        networks:
            - the_network
        depends_on:
            - redis_db
            - snmpd
        container_name: sender
        #entrypoint: /bin/bash
        tty: true
        stdin_open: true

networks:
    the_network:
        name: the_network
        driver: bridge