version: "3.8"
services:

    redis_db:
        image: redis:latest
        ports:
            - "6379"
        networks:
            - the_network
        container_name: redis_db  
        tty: true
        stdin_open: true   

    snmpd:
        build:
            context: ../snmpd/.
            dockerfile: ../dockerfiles/build-snmpd
        networks:
            - the_network
        depends_on:
            - redis_db
        container_name: snmpd
        tty: true
        stdin_open: true

    sender:
        build:
            context: ../sender/.
            dockerfile: ../dockerfiles/snmp-sender
        networks:
            - the_network
        depends_on:
            - redis_db
            - snmpd
        volumes: 
            - /home/user2/work/idf/netsnmp/sender:/sender
        environment:
            - SERVER_HOST=sam-server
            - SERVER_PORT=3044
            - PRIV_PASS=yuval12345
            - AUTH_PASS=yuval12321
        container_name: sender
        entrypoint: /bin/bash
        tty: true
        stdin_open: true

    server:
        --net host --env PORT_TCP_SNMP=3044 
        image: samyon196/snmp_demo_server:1.0.0
        environments:
            - PORT_TCP_SNMP=3044
        networks:
            - the_network
        container_name: sam-server
        tty: true
        stdin_open: true


networks:
    the_network:
        name: the_network
        driver: bridge