version: "3.8"
services:

    redis_db:
        image: redis:latest
        ports:
            - "6379"
        networks:
            - the_network
        container_name: redis_db     

    python:
        build:
            context: ../sender/.
            dockerfile: ../dockerfiles/snmp-sender
        tty: true
        stdin_open: true
        networks:
            - the_network
        depends_on:
            - redis_db
        container_name: py_cont

networks:
    the_network:
        name: the_network
        driver: bridge